defmodule RoomboardRealtimeWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :roomboard_realtime

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_roomboard_realtime_key",
    signing_salt: "s8GWyycv",
    same_site: "Lax"
  ]

  socket "/socket", RoomboardRealtimeWeb.UserSocket,
    websocket: [
      check_origin: {RoomboardRealtimeWeb.Endpoint, :allowed_origin?, []}
    ],
    longpoll: false

  def allowed_origin?(%URI{} = origin) do
    case Application.get_env(:roomboard_realtime, :allowed_origins, []) do
      :any -> true
      origins when is_list(origins) -> Enum.any?(origins, &origin_matches?(&1, origin))
      _ -> false
    end
  end

  defp origin_matches?(allowed_origin, %URI{} = origin) when is_binary(allowed_origin) do
    case URI.parse(allowed_origin) do
      %URI{host: host} = allowed when is_binary(host) ->
        scheme_matches?(allowed.scheme, origin.scheme) and
          host_matches?(host, origin.host) and
          port_matches?(allowed.port, origin.port)

      _ ->
        false
    end
  end

  defp origin_matches?(_allowed_origin, _origin), do: false

  defp scheme_matches?(nil, _origin_scheme), do: true
  defp scheme_matches?(scheme, scheme), do: true
  defp scheme_matches?(_allowed_scheme, _origin_scheme), do: false

  defp host_matches?(_allowed_host, nil), do: false

  defp host_matches?("*." <> suffix, origin_host) do
    origin_host = String.downcase(origin_host)
    suffix = String.downcase(suffix)
    String.ends_with?(origin_host, "." <> suffix)
  end

  defp host_matches?(allowed_host, origin_host) do
    String.downcase(allowed_host) == String.downcase(origin_host)
  end

  defp port_matches?(nil, _origin_port), do: true
  defp port_matches?(port, port), do: true
  defp port_matches?(_allowed_port, _origin_port), do: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :roomboard_realtime,
    gzip: not code_reloading?,
    only: RoomboardRealtimeWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Wrap `Plug.Parsers` so a malformed JSON body on the internal-event
  # endpoint surfaces as a 422 in the controller (the wrapper stashes the
  # `Plug.Parsers.ParseError` on `conn.assigns`) rather than as a 400
  # bubbled up from a parser crash. The standard parsers run unchanged for
  # every other route.
  plug RoomboardRealtimeWeb.WrapPlugParsers,
    parsers: [:urlencoded, :multipart, :json],
    json_decoder: Phoenix.json_library(),
    # Cache the raw request body so the internal-event controller can verify
    # an HMAC over the exact bytes the caller signed — re-serializing the
    # decoded params would re-order keys and break the signature.
    body_reader: {RoomboardRealtimeWeb.CacheBodyReader, :read_body, []}

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug RoomboardRealtimeWeb.Router
end
